#%RAML 1.0 NamedExample
errorResponse: {
  "status": "Failure",
  "message": "Error occured while processing",
  "errorDetails": {
        "code": "400",
        "message": "Quote ID is unavailable",
        "errorType": "CORESYSTEM_ERROR",
        "timeStamp" : "2023-01-31T09:13:40.696-Z"
    }
}
