#%RAML 1.0 NamedExample
policyQuotationRequest: {
  "customer": {
    "fisrtName":"John",
    "lastName":"Doe",
    "dob":"01/01/1991",
    "email":"john.doe@email.com"
  },
  "travelDetails": {
    "destination":"Singapore",
    "departureDate":"01/01/2023",
    "returnDate":"11/01/2023"
    }
}