#%RAML 1.0 NamedExample
policyQuotationResponse: {
  "quoteId": "167e4af6-a121-11ed-a8fc-0242ac120002",
  "insurancePlan": [{
    "planName": "gold",
    "premium": 100
  },
  {
    "planName": "silver",
    "premium": 80
  },
  {
    "planName": "platinum",
    "premium": 120
  }]
}