#%RAML 1.0 DataType

type: object
properties:
  quoteId:
    type: string
    description: Quotation Id
    example: "167e4af6-a121-11ed-a8fc-0242ac120002"
  planName:
    type: string
    description: Plan Name
    example: "Silver"
